### ISSUE TITLE
Please make a blog on django k8s ngnix ingress cert and helm chart-values.

### ISSUE THREAD

**Issue by ghost** [yvsssantosh/django-polls-rest#1]
The django-k8s blog is awesome and very helpful. But i need ngnix ingress and cert for free ssl. Please help me to build a django app in k8s with ngnix ingress, cert manager ssl with helm template.
___ Thanks

**Comment by yvsssantosh** [comment]
Thank you for going through the blog. Sure will make some time this weekend and make a blog for that as well
